### ISSUE TITLE
azure devops --releasify 

### ISSUE THREAD

**Issue by greengumby** [Squirrel/Squirrel.Windows#1580]
Can anyone provide any guidance on how to perform a --releasify on azure devops yaml pipeline.
I have tried cmdline@2 but this always results in a exit code of -1 and no futher detail.
Thanks

**Comment by lightlike** [comment]
I did that for my own project. Debugging is very annoying when you do not get any error codes.

What I did is download the Squirrel executables as a zip and unpack them.
After that, I used the command at the bottom to `--releasify` an already created nupkg.

I have not found out why, but if you are using certain hosted agents (e.g. release-agents) the creation of delta-packages will not work. (Probably because some system stuff is not installed on those light-weight machines)

``` yaml
variables:
  Version: '$(Build.BuildNumber)'

steps:
- task: CmdLine@1
  displayName: 'Releasify Squirrel'
  inputs:
    filename: '$(System.DefaultWorkingDirectory)/Squirrel/Squirrel.exe'
    arguments: '--releasify $(System.DefaultWorkingDirectory)\Release\*NupkgName*.$(Version).nupkg -r $(System.DefaultWorkingDirectory)\Output -n "/a /f $(pfx.secureFilePath) /p $(Sign.Password)" --framework-version=net461 --no-msi'
    workingFolder: '$(System.DefaultWorkingDirectory)\Release'
```

**Comment by greengumby** [comment]
Thanks @lightlike 

For some reason I get the following output from the cmd. Hoping you had come across the same issue.

```
##[section]Starting: Releasify Squirrel
==============================================================================
Task         : Command Line
Description  : Run a command line with arguments
Version      : 1.1.3
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
==============================================================================
##[command]D:\a\1\packages\squirrel.windows.1.9.1\tools\Squirrel.exe --releasify D:\a\1\a\nuget\XXX.1.0.20200120.7.nupkg --releaseDir D:\a\1\a\drop
##[error]Process completed with exit code -1.
##[section]Finishing: Releasify Squirrel
```

The yaml I am using is

`- task: CmdLine@1
  displayName: 'Releasify Squirrel'
  inputs:
    filename: 'D:\a\1\packages\squirrel.windows.1.9.1\tools\Squirrel.exe'
    arguments: '--releasify $(build.ArtifactStagingDirectory)\nuget\XXX.$(Build.BuildNumber).nupkg --releaseDir $(build.ArtifactStagingDirectory)\drop'
    workingFolder: '$(build.ArtifactStagingDirectory)\drop'`


Thanks for your help

**Comment by lightlike** [comment]
That command should work.

The next thing I would test is either the nupkg or try `--no-msi` (at least I think that I had a reason to put that in the command).
The problem might also be the squirrel.exe in the nuget package. Maybe test that too. 

Maybe it would be a good idea to download the build-output and test this on your computer. That should be much faster.
It might also be a good idea, if you do the packaging and the releasifying in a release pipeline. It is much faster that way, if you do not have to build the project every time.

I would also advise against project packaging, if you are using that. Some nuget-stuff might conflict with squirrel. 
The nuspec I use is [this one](https://github.com/Drachenhorn-Team/Drachenhorn/blob/master/Drachenhorn.Desktop/Drachenhorn.nuspec).

**Comment by Rodric75** [comment]
Never used azure pipelines before, can either/both of you post a bit more guidance?  yaml samples / steps / youtube explanation / blog walkthrough / consulting agreement?  Pretty much anything helps. @lightlike @greengumby

**Comment by lightlike** [comment]
@Rodric75 

I mostly use the overlay instead of YAML. But I could imagine it is fairly easy to generate one from that.

I split the work into two Pipelines

1. Normal Release Build Configuration, pushing the relevant files as artifacts
2. Release Configuration with the following steps based on the Build Artifacts of 1

![Release Steps](https://user-images.githubusercontent.com/12970722/73107369-f79b0080-3efd-11ea-9944-8cd5d310f261.png)

Most of this should be pretty self explanatory but the command I use for the `releasify` is:
``` cmd
--releasify $(System.DefaultWorkingDirectory)\Release\Drachenhorn.$(Version).nupkg -r $(System.DefaultWorkingDirectory)\Output -n "/a /f $(pfx.secureFilePath) /p $(Sign.Password)" --framework-version=net461 --no-msi
```

If you want to see the project and the result. You can find that [here](https://github.com/Drachenhorn-Team/Drachenhorn).

I first had the releasify inside the build itself but that was far to annoying to test because every time it had to rebuild everything and pull all the nuget packages for net-standard which too some time.
But now I can no longer generate any Delta-Packages until I get my own agent up and running.

The most annoying part is testing and fixing anything that goes wrong. But that just takes time and many tries.

**Comment by Rodric75** [comment]
Having some issues extracting the squirrel zip file?  Can you show the yaml for those 2 steps?

Sent from my iPad

On Jan 24, 2020, at 4:24 PM, DanielN <notifications@github.com> wrote:

﻿

@Rodric75<https://github.com/Rodric75>

I mostly use the overlay instead of YAML. But I could imagine it is fairly easy to generate one from that.

I split the work into two Pipelines

  1.  Normal Release Build Configuration, pushing the relevant files as artifacts
  2.  Release Configuration with the following steps based on the Build Artifacts of 1

[Release Steps]<https://user-images.githubusercontent.com/12970722/73107369-f79b0080-3efd-11ea-9944-8cd5d310f261.png>

Most of this should be pretty self explanatory but the command I use for the releasify is:

--releasify $(System.DefaultWorkingDirectory)\Release\Drachenhorn.$(Version).nupkg -r $(System.DefaultWorkingDirectory)\Output -n "/a /f $(pfx.secureFilePath) /p $(Sign.Password)" --framework-version=net461 --no-msi

If you want to see the project and the result. You can find that here<https://github.com/Drachenhorn-Team/Drachenhorn>.

I first had the releasify inside the build itself but that was far to annoying to test because every time it had to rebuild everything and pull all the nuget packages for net-standard which too some time.
But now I can no longer generate any Delta-Packages until I get my own agent up and running.

The most annoying part is testing and fixing anything that goes wrong. But that just takes time and many tries.

**Comment by lightlike** [comment]
The Squirrel.zip is just one, that I packed from the release of Squirrel here on Github.

The dowload is simply a "secure file download" task:
``` YAML
steps:
- task: DownloadSecureFile@1
  displayName: 'Download Squirrel'
  inputs:
    secureFile: Squirrel.zip
```

The unzip is something you can get from the marketplace and just takes the output path from the download task and unzips based on that. 
``` YAML
steps:
- task: ExtractFiles@1
  displayName: 'Extract Squirrel'
  inputs:
    archiveFilePatterns: '$(Squirrel.secureFilePath)'
    destinationFolder: '$(System.DefaultWorkingDirectory)/Squirrel'
```

**Comment by MovGP0** [comment]
I am wondering if I can just use Azure DevOps integrated NuGet feed for updates. This way, there would be no changes needed to the build pipeline.

**Comment by lightlike** [comment]
I don't think that would work, as you would need to also download the RELEASE textfile from the same base url and I do not think that the nuget feed would allow non-nupkg files.
I might work if you wrote your own UpdateManager or do some workaroundy stuff.

**Comment by MovGP0** [comment]
Then don't use a RELEASE textfile. The NuGet feed itself should provide enough information to support the update process.

**Comment by uygary** [comment]
I bet it could be made work, but it'd be a breaking change for all the production apps that currently use Squirrel.
Feel free to create a fork that does exactly what you need though.

**Comment by lightlike** [comment]
@MovGP0 As I said, that could work but you would need to create your own UpdateManager or at lease overload the download functionality of the existing ones. Feel free to do that.

@uygary This could also work in default squirrel if you make it a new UpdateManager like the GitHubUpdateManager. The setup does not need any nupkg-Files so I don't see any problem with that. But I do not know if it would be accepted though.

**Comment by gabrielbarceloscn** [comment]
Here's my WORKING build pipeline using Azure DevOps. 

Important facts:
1. It's using Squirrel 2.0.1
2. I've installed an extension named [Assembly Info Reader](https://marketplace.visualstudio.com/items?itemName=kherzog.AssemblyInfoReader) to get Assembly Version. 
3. I've lost so much time with problems caused by slash/backslash.
4. Working directory is important when running power shell and command line operations.
5. I´m storing binary in an [Azure Blog Storage](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction).
6. Before build a new installer, I need to download previous version, along with the RELEASES file, and .NUPKG to create a DELTA and append to RELEASES file, new version information.
7. Nuget tools are already installed in this [Windows Hosted Image](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md). 
8. I´m using Azure CLI to invoke [az storage blob](https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest) commands. I´m in an authenticated connection inside Azure DevOps.
9. I´m using a MONOREPO strategy. *Modules* folder have 5 distinct projects. Then I´m using *path filters* with my continuous build process.

```yaml
trigger:
 branches:
   include:
     - main
 paths:
   include:
     - modules/frontendDesktop/src/*
   exclude:
     - modules/frontendDesktop/docs
     - modules/frontendDesktop/img
     - modules/frontendDesktop/dist
     - modules/frontendDesktop/tools
     - modules/frontendDesktop/tests
     - modules/frontendDesktop/installer

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'modules/frontendDesktop/ErpFrontendDesktop.sln'
  projectFolder: 'modules/frontendDesktop/src/pos.winforms'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: AssembyInfoReader@2
  displayName: 'Get Assembly Info'
  inputs:
    searchPattern: '$(projectFolder)/Properties/AssemblyInfo.cs'

- task: NuGetCommand@2
  displayName: 'NuGet Restore'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: 'UI Tests'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PowerShell@2
  displayName: 'Create folder \PosDesk\Prod'
  inputs:
    targetType: 'inline'
    workingDirectory: '$(projectFolder)'
    script: "mkdir -p bin/posdesktop/production"

- task: AzureCLI@2
  displayName: 'Download previous installer'
  inputs:
    azureSubscription: 'Azure-TCS-Erp'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: '
      az storage blob download-batch 
        --source appreleases
        --pattern posdesktop/production/*
        --destination bin 
        --account-key $(stor_releases_key) 
        --account-name sterppublic'
    workingDirectory: '$(projectFolder)'

- task: PowerShell@2
  displayName: 'Create folder \ReleasePublish'
  inputs:
    targetType: 'inline'
    workingDirectory: '$(projectFolder)'
    script: "mkdir -p bin/releasePublish"

- task: PowerShell@2
  displayName: 'Copy to Release Publish'
  inputs:
    targetType: 'inline'
    workingDirectory: '$(projectFolder)'
    script: "mv bin/posdesktop/production/* bin/releasePublish"

- task: CmdLine@2
  displayName: 'Create .nupkg'
  inputs:
    script: 'nuget pack BuildPipeline\PosWinforms.nuspec 
                -Version $(AssemblyInfo.AssemblyVersion) 
                -Properties Configuration=Release 
                -OutputDirectory bin\releasePkg
            '
    workingDirectory: '$(projectFolder)'

- task: CmdLine@2
  displayName: 'Create Installer'
  inputs:
    script: '..\..\packages\squirrel.windows.2.0.1\tools\squirrel 
                --releasify bin\releasePkg\PosWin.$(AssemblyInfo.AssemblyVersion).nupkg 
                -r bin\releasePublish 
                --setupIcon Icon.ico 
                --no-msi'
    workingDirectory: '$(projectFolder)'
    failOnStderr: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Installer'
  inputs:
    PathtoPublish: '$(projectFolder)/bin/releasePublish'
    ArtifactName: 'squirrel_release'
    publishLocation: 'Container'
```
